import { createHash, randomUUID } from 'node:crypto';
import { eq, inArray, sql } from 'drizzle-orm';
import type { FileInfo, FilePurpose, FileRef } from '@edventure/contracts';
import { createUploadRequest, uploadRules, type z } from '@edventure/contracts';
import type { Config } from '../../config';
import type { Db, Tx } from '../../db/client';
import { files } from '../../db/schema';
import { withTenant } from '../../db/tenant';
import type { JobQueue } from '../../jobs/queue';
import { isAdmin, tenantOf, type Actor } from '../../platform/actor';
import { audit } from '../../platform/audit';
import { AppError, errors, required } from '../../platform/errors';
import { today } from '../../platform/scope';
import type { StorageProvider } from '../../storage/provider';

type FileRow = typeof files.$inferSelect;

/** Purposes whose downloads are proxied through the API instead of a signed storage URL. */
const SENSITIVE: FilePurpose[] = ['document', 'report', 'export', 'import', 'profile_image'];

export function sniffMimeType(head: Buffer): string | null {
  if (head.subarray(0, 5).toString('latin1') === '%PDF-') return 'application/pdf';
  if (head[0] === 0x89 && head.subarray(1, 4).toString('latin1') === 'PNG') return 'image/png';
  if (head[0] === 0xff && head[1] === 0xd8 && head[2] === 0xff) return 'image/jpeg';
  if (!head.includes(0)) {
    try {
      new TextDecoder('utf-8', { fatal: true }).decode(head);
      return 'text/csv';
    } catch {
      return null;
    }
  }
  return null;
}

export const toFileInfo = (f: FileRow): FileInfo => ({
  id: f.id,
  name: f.originalName,
  mimeType: f.mimeType,
  sizeBytes: f.sizeBytes,
  purpose: f.purpose,
  scanState: f.scanState,
  lifecycle: f.lifecycle,
  createdAt: f.createdAt.toISOString(),
});

export const toFileRef = (f: FileRow): FileRef => ({
  id: f.id,
  name: f.originalName,
  mimeType: f.mimeType,
  sizeBytes: f.sizeBytes,
  available: f.lifecycle === 'available',
});

/**
 * Upload: authorize → upload intent → client uploads to quarantine → verify size/type/checksum →
 * malware scan → available → attach to a permitted record. Downloads are authorized through the
 * business record the file is attached to.
 */
export class FilesService {
  constructor(
    private readonly db: Db,
    private readonly storage: StorageProvider,
    private readonly jobs: JobQueue,
    private readonly config: Config,
  ) {}

  private run<T>(actor: Actor, fn: (tx: Tx) => Promise<T>) {
    return withTenant(this.db, tenantOf(actor), fn);
  }

  async createUpload(actor: Actor, raw: z.input<typeof createUploadRequest>) {
    const input = createUploadRequest.parse(raw);
    const rule = uploadRules[input.purpose];
    if (!rule.clientUpload) throw errors.forbidden('This file type is generated by the system');
    const mime = input.mimeType === 'application/vnd.ms-excel' && input.purpose === 'import' ? 'text/csv' : input.mimeType;
    if (!rule.mimeTypes.includes(mime)) throw errors.field('mimeType', `Allowed types: ${rule.mimeTypes.join(', ')}`);
    if (input.sizeBytes > rule.maxBytes) throw errors.field('sizeBytes', `The file must be ${Math.round(rule.maxBytes / 1024 / 1024)} MB or smaller`);
    if (/\.(exe|bat|cmd|sh|js|html?|svg|zip|rar|7z|docm|xlsm|pptm)$/i.test(input.fileName)) throw errors.field('fileName', 'This kind of file is not accepted');
    if (input.purpose === 'import' && !isAdmin(actor)) throw errors.forbidden();
    const id = randomUUID();
    const now = new Date();
    const objectKey = `${actor.schoolId}/${input.purpose}/${now.getUTCFullYear()}/${String(now.getUTCMonth() + 1).padStart(2, '0')}/${id}`;
    const row = await this.run(actor, async (tx) => {
      const [f] = await tx
        .insert(files)
        .values({
          id,
          schoolId: actor.schoolId,
          objectKey,
          originalName: input.fileName.replace(/[\\/:*?"<>|\u0000-\u001f]/g, '_'),
          mimeType: mime,
          sizeBytes: input.sizeBytes,
          purpose: input.purpose,
          uploadedByAccountId: actor.accountId,
          expiresAt: new Date(Date.now() + 24 * 3600 * 1000),
        })
        .returning();
      return f!;
    });
    const upload = await this.storage.createUploadTarget(objectKey, mime, rule.maxBytes);
    return { file: toFileInfo(row), upload: { ...upload, expiresAt: upload.expiresAt.toISOString() } };
  }

  /** Verifies the uploaded object and moves it to quarantine for scanning. */
  async complete(actor: Actor, fileId: string) {
    const row = await this.run(actor, async (tx) => {
      const [f] = await tx.select().from(files).where(eq(files.id, fileId)).for('update');
      const file = required(f, 'File');
      if (file.uploadedByAccountId !== actor.accountId) throw errors.forbidden();
      if (file.lifecycle !== 'upload_pending') return file;
      return file;
    });
    if (row.lifecycle !== 'upload_pending') return toFileInfo(row);
    const stat = await this.storage.stat(row.objectKey);
    const rule = uploadRules[row.purpose];
    let rejection: string | null = null;
    let checksum: string | null = null;
    if (!stat) rejection = 'The upload did not arrive. Please try again.';
    else if (stat.size > rule.maxBytes || stat.size === 0) rejection = 'The file size is not allowed.';
    else {
      const body = await this.storage.read(row.objectKey);
      const sniffed = sniffMimeType(body.subarray(0, 4096));
      if (!sniffed || sniffed !== row.mimeType) rejection = 'The file content does not match its type.';
      checksum = createHash('sha256').update(body).digest('hex');
    }
    const skipScan = this.config.SKIP_MALWARE_SCAN && !this.config.isProduction;
    const updated = await this.run(actor, async (tx) => {
      if (rejection) {
        const [f] = await tx.update(files).set({ lifecycle: 'rejected', rejectionReason: rejection }).where(eq(files.id, fileId)).returning();
        return f!;
      }
      const [f] = await tx
        .update(files)
        .set({
          sizeBytes: stat!.size,
          checksumSha256: checksum,
          lifecycle: skipScan ? 'available' : 'quarantine',
          scanState: skipScan ? 'skipped' : 'pending',
          availableAt: skipScan ? new Date() : null,
          expiresAt: null,
        })
        .where(eq(files.id, fileId))
        .returning();
      if (!skipScan) await this.jobs.enqueue(tx, 'fileScan', { schoolId: actor.schoolId, fileId });
      return f!;
    });
    if (rejection) {
      await this.storage.remove(row.objectKey).catch(() => undefined);
      throw new AppError('unsupported_media_type', rejection);
    }
    return toFileInfo(updated);
  }

  /** Called by the worker after scanning. */
  async recordScan(actor: Actor, fileId: string, result: 'clean' | 'infected' | 'failed') {
    const file = await this.run(actor, async (tx) => {
      const [f] = await tx
        .update(files)
        .set(
          result === 'clean'
            ? { scanState: 'clean', lifecycle: 'available', availableAt: new Date() }
            : result === 'infected'
              ? { scanState: 'infected', lifecycle: 'rejected', rejectionReason: 'The file failed the malware scan.' }
              : { scanState: 'failed' },
        )
        .where(eq(files.id, fileId))
        .returning();
      await audit(tx, actor, { action: `file.scan_${result}`, entityType: 'file', entityId: fileId });
      return f;
    });
    if (file && result === 'infected') await this.storage.remove(file.objectKey).catch(() => undefined);
  }

  /** Files the actor may attach: their own uploads (or any, for admins) that were not rejected. */
  async assertAttachable(tx: Tx, actor: Actor, fileIds: string[], purposes: FilePurpose[]) {
    if (!fileIds.length) return [];
    const rows = await tx.select().from(files).where(inArray(files.id, fileIds));
    for (const id of fileIds) {
      const f = rows.find((r) => r.id === id);
      if (!f || !purposes.includes(f.purpose) || !['quarantine', 'available'].includes(f.lifecycle)) {
        throw errors.field('attachments', 'An attachment is missing, still uploading or was rejected');
      }
      if (!isAdmin(actor) && f.uploadedByAccountId !== actor.accountId) throw errors.forbidden('You can only attach your own uploads');
    }
    return rows;
  }

  async refs(tx: Tx, fileIds: string[]): Promise<FileRef[]> {
    if (!fileIds.length) return [];
    const rows = await tx.select().from(files).where(inArray(files.id, fileIds));
    return fileIds.map((id) => rows.find((r) => r.id === id)).filter((r): r is FileRow => !!r).map(toFileRef);
  }

  private async canAccess(tx: Tx, actor: Actor, file: FileRow) {
    if (file.uploadedByAccountId === actor.accountId) return true;
    if (isAdmin(actor) && file.purpose !== 'report') return true;
    const date = today(actor);
    const [row] = await tx.execute<{ ok: boolean }>(sql`
      select (
        -- Homework attachments: teachers of the group and recipients
        exists (select 1 from app.homework_attachments ha join app.homework h on h.id = ha.homework_id
          where ha.file_id = ${file.id} and (
            exists (select 1 from app.homework_recipients r where r.homework_id = h.id and r.student_id = ${actor.studentId})
            or exists (select 1 from app.teacher_assignments ta where ta.teaching_group_id = h.teaching_group_id and ta.teacher_id = ${actor.teacherId}
              and (ta.end_date is null or ta.end_date > ${date}))))
        -- Submissions: the submitting student and the group's teachers
        or exists (select 1 from app.submission_attachments sa join app.homework_submissions s on s.id = sa.submission_id
          join app.homework_recipients r on r.id = s.recipient_id join app.homework h on h.id = r.homework_id
          where sa.file_id = ${file.id} and (r.student_id = ${actor.studentId}
            or exists (select 1 from app.teacher_assignments ta where ta.teaching_group_id = h.teaching_group_id and ta.teacher_id = ${actor.teacherId}
              and (ta.end_date is null or ta.end_date > ${date}))))
        -- Learning materials: group members and teachers
        or exists (select 1 from app.learning_materials lm where lm.file_id = ${file.id} and lm.archived_at is null and (
            exists (select 1 from app.teaching_group_memberships m where m.teaching_group_id = lm.teaching_group_id and m.student_id = ${actor.studentId}
              and (m.end_date is null or m.end_date > ${date}))
            or exists (select 1 from app.teacher_assignments ta where ta.teaching_group_id = lm.teaching_group_id and ta.teacher_id = ${actor.teacherId}
              and (ta.end_date is null or ta.end_date > ${date}))))
        -- Announcement attachments: recipients
        or exists (select 1 from app.announcement_attachments aa
          join app.notifications n on n.entity_type = 'announcement' and n.entity_id = aa.announcement_id
          join app.notification_recipients nr on nr.notification_id = n.id and nr.account_id = ${actor.accountId}
          where aa.file_id = ${file.id})
        -- Personal documents and reports
        or exists (select 1 from app.student_documents d where d.file_id = ${file.id} and d.student_id = ${actor.studentId})
        or exists (select 1 from app.teacher_documents d where d.file_id = ${file.id} and d.teacher_id = ${actor.teacherId})
        or exists (select 1 from app.report_jobs j where j.file_id = ${file.id} and j.requested_by_account_id = ${actor.accountId})
      ) as ok`);
    return row?.ok === true;
  }

  async info(actor: Actor, fileId: string) {
    return this.run(actor, async (tx) => {
      const [f] = await tx.select().from(files).where(eq(files.id, fileId));
      const file = required(f, 'File');
      if (!(await this.canAccess(tx, actor, file))) throw errors.notFound('File');
      return toFileInfo(file);
    });
  }

  /** Short-lived link. Sensitive files are proxied through the authenticated content endpoint. */
  async download(actor: Actor, fileId: string) {
    const file = await this.run(actor, async (tx) => {
      const [f] = await tx.select().from(files).where(eq(files.id, fileId));
      const found = required(f, 'File');
      if (!(await this.canAccess(tx, actor, found))) throw errors.notFound('File');
      return found;
    });
    if (file.lifecycle !== 'available') {
      throw new AppError('conflict', file.lifecycle === 'quarantine' ? 'This file is still being checked. Try again shortly.' : 'This file is no longer available.');
    }
    if (file.expiresAt && file.expiresAt < new Date()) throw new AppError('conflict', 'This download has expired. Generate it again.');
    const expiresInSeconds = 5 * 60;
    const expiresAt = new Date(Date.now() + expiresInSeconds * 1000).toISOString();
    if (SENSITIVE.includes(file.purpose)) return { url: `/api/v1/files/${file.id}/content`, expiresAt };
    return { url: await this.storage.createDownloadUrl(file.objectKey, file.originalName, expiresInSeconds), expiresAt };
  }

  async content(actor: Actor, fileId: string) {
    const file = await this.run(actor, async (tx) => {
      const [f] = await tx.select().from(files).where(eq(files.id, fileId));
      const found = required(f, 'File');
      if (!(await this.canAccess(tx, actor, found))) throw errors.notFound('File');
      return found;
    });
    if (file.lifecycle !== 'available') throw new AppError('conflict', 'This file is not available.');
    if (file.expiresAt && file.expiresAt < new Date()) throw new AppError('conflict', 'This download has expired.');
    return { body: await this.storage.read(file.objectKey), mimeType: file.mimeType, name: file.originalName };
  }

  /** Stores a server-generated file (exports, reports) as available, with an expiry. */
  async storeGenerated(tx: Tx, actor: Actor, input: { purpose: 'export' | 'report'; name: string; mimeType: string; body: Buffer; expiresInHours: number }) {
    const id = randomUUID();
    const objectKey = `${actor.schoolId}/${input.purpose}/${id}`;
    await this.storage.write(objectKey, input.body, input.mimeType);
    const [f] = await tx
      .insert(files)
      .values({
        id,
        schoolId: actor.schoolId,
        objectKey,
        originalName: input.name,
        mimeType: input.mimeType,
        sizeBytes: input.body.length,
        checksumSha256: createHash('sha256').update(input.body).digest('hex'),
        purpose: input.purpose,
        scanState: 'skipped',
        lifecycle: 'available',
        availableAt: new Date(),
        expiresAt: new Date(Date.now() + input.expiresInHours * 3600 * 1000),
        uploadedByAccountId: actor.client === 'system' ? null : actor.accountId,
      })
      .returning();
    return f!;
  }

  async remove(actor: Actor, fileId: string) {
    const file = await this.run(actor, async (tx) => {
      const [f] = await tx.select().from(files).where(eq(files.id, fileId)).for('update');
      const found = required(f, 'File');
      if (found.uploadedByAccountId !== actor.accountId && !isAdmin(actor)) throw errors.forbidden();
      const [attached] = await tx.execute<{ used: boolean }>(sql`
        select exists (select 1 from app.homework_attachments where file_id = ${fileId})
          or exists (select 1 from app.submission_attachments where file_id = ${fileId})
          or exists (select 1 from app.learning_materials where file_id = ${fileId} and archived_at is null)
          or exists (select 1 from app.announcement_attachments where file_id = ${fileId}) as used`);
      if (attached?.used) throw errors.rule('This file is attached to a record. Remove it there first.');
      await tx.update(files).set({ lifecycle: 'deleted', deletedAt: new Date() }).where(eq(files.id, fileId));
      return found;
    });
    await this.storage.remove(file.objectKey).catch(() => undefined);
  }

  get storageProvider() {
    return this.storage;
  }
}
