/**
 * Private object storage. Object keys are generated by the application (never user file names);
 * every download is authorized by the backend before a short-lived link is issued.
 */
export interface UploadTarget {
  url: string;
  method: 'PUT';
  headers: Record<string, string>;
  expiresAt: Date;
}

export interface StorageProvider {
  readonly kind: 'local' | 'supabase';
  createUploadTarget(objectKey: string, mimeType: string, maxBytes: number): Promise<UploadTarget>;
  stat(objectKey: string): Promise<{ size: number } | null>;
  read(objectKey: string): Promise<Buffer>;
  write(objectKey: string, body: Buffer, mimeType: string): Promise<void>;
  createDownloadUrl(objectKey: string, fileName: string, expiresInSeconds: number): Promise<string>;
  remove(objectKey: string): Promise<void>;
}
