export * from './core';
export * from './people';
export * from './academics';
export * from './timetable';
export * from './attendance';
export * from './learning';
export * from './assessment';
export * from './finance';
export * from './operations';
